### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by aswarren** [evogytis/B.1.620-in-Europe#1]
Was curious if it was intentional to leave 
```data/travel_qc_info.csv```
out of  the repo?
It is referenced in https://github.com/evogytis/B.1.620-in-Europe/blob/main/scripts/B.1.620-circular-map.ipynb
Great looking plot!
Thanks!

**Comment by BEAST-Community** [comment]
Could this all figures plotted by R?

**Comment by evogytis** [comment]
Hey Andrew,

Apologies for the original omission, it should be fixed now. I'm hoping to include an example based on the plot you're referring to in the baltic gallery: https://phylo-baltic.github.io/baltic-gallery/
